### ISSUE TITLE
No display and looking for temperature offset

### ISSUE THREAD

**Issue by gadg3ts** [chad-ermacora/sensor-rp#17]
Hi, 
I've got the package running on a Pi ZeroW with an Enviro+ and it's giving me data, which is great.
However, there are a couple of things perplexing me which I'm hoping you can help shed some light on.
1) The display after boot shows for a while  " -- Sens" which I'm guessing is short for " -- Sensor Display Server Started" that's in the code. I'm guessing that the subsequent display of temperature etc is offset somewhere as it's not showing. How can I find if that's the case?
2) Is there any way to set a temperature offset multiplier? as opposed to just an offset in degrees - given that on the Enviro+ especially the cpu temp affects the temp sensor on the hat.

Thanks,
Sean

**Comment by chad-ermacora** [comment]
Hello Sean and thanks for posting.

I have been neglecting the display support, as I have yet to think of how I want it to operate. That being said, the subsequent displays are the raw CPU temperature and then the raw Environmental Temperature before any adjustments such as the 'Environmental Temperature Offset'.  

As of now, there is no multiplier offset option, but that does sound like a good idea.  I'll look into implementing it in the future. 

Also if you have any suggestions on how you would like the displays to operate, let me know and I'll see what I can do.  To start, I was thinking of allowing the user to select what sensors it displays and the frequency of which it displays them, as well as the option of showing a graph for one or more sensors.

**Comment by gadg3ts** [comment]
I guess a value or three with a graph would be ideal for the small display - temp/humidity/pressure might be a good start :)
The pimoroni tutorials here
https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-enviro-plus
have a nice-looking graph but I've not been able to replicate it yet.
I've managed to hack about with the example code for the enviro+ libraries, but my python isn't (yet) as good as my bash. 
My eventual aim for the board was to make something like a Nest Thermostat but being able to wave at it to change the temperature setting, so anything that makes collecting those values (like this project) is great :)

**Comment by chad-ermacora** [comment]
I have added a section for configuring the display settings now. It's just basic to start (choose what text readings to show and how often) but I'll see about adding in the graphing part before I release it into the stable channel. 

If you use the "Dev - HTTP Upgrade" under Developmental Upgrades, you can check it out.

**Comment by chad-ermacora** [comment]
I have added Temperature compensation based on the Raspberry Pi's own CPU Temperature sensor.  The formula is as follows.

(RawTemperature + Offset) - ((PiTemperature - RawTemperature) x CorrectionFactor).

I will continue to enhance the Display section as time allows.
