### ISSUE TITLE
MQTT or API Support

### ISSUE THREAD

**Issue by NicNacke** [chad-ermacora/sensor-rp#18]
Hi,
i have also an Enviro+ on an Pi ZeroW and it works fine.

But I want to ask if it possible to integrate MQTT and/or API support.

MQTT for example to send the data to a system like Home Assistant.
Or an API that provides the data as JSON so that you can query the data yourself.

Thanks,
Jochen

**Comment by chad-ermacora** [comment]
Hello,

I'm happy to hear Kootnet Sensors is working for you ^_^ 

As for your question, I do have a basic HTTPS API setup to get text readings of individual sensors.  For example, you can go to the following URL to get the Environmental Temperature sensor reading (replacing SensorIP with your actual sensor's IP or hostname). 

`https://SensorIP:10065/GetEnvTemperature`

I have yet to create a document of the available URL's but you can find the corresponding links in the following file.

[text_sensor_readings.py](https://github.com/chad-ermacora/sensor-rp/blob/master/http_server/flask_blueprints/text_sensor_readings.py)

I also like the idea of MQTT, as I have heard that term used a decent amount out there.  So I'll see about adding support. I should also be able to add JSON support easily enough.

**Comment by chad-ermacora** [comment]
I have MQTT working on a very basic level, but I was hoping to get some feedback on how I should publish the readings to the broker.  

I was thinking maybe sending all available readings in JSON format as a string or creating a Topic per sensor ... or both?

**Comment by NicNacke** [comment]
I think both (JSON format and one Topic per sensor) are good ideas. So the user can decide what to use.

I use Home Assistant and with one topic per sensor I could process the data faster. But that's just my opinion. I think others prefer JSON to process in other systems.

**Comment by chad-ermacora** [comment]
I have MQTT working as a Publisher sending with a topic per sensor.  Sensors with multiple readings are sent as CSV text.  I have uploaded the new version to the developmental channel if you wanted to check it out.  

It will still be a bit before I release this into the Stable (master) branch as I want to allow an MQTT broker to be run on the local sensor if desired and allow sending all readings in JSON format.

**Comment by NicNacke** [comment]
Thank you for your Work.

I am very busy at the moment, but I will test it in the next few days.

**Comment by chad-ermacora** [comment]
You're welcome! 

A few more days should give me time to run through more tests and ensure less or no bugs.  

FYI: Upgrading to a development build can be found in the web interface under "Local Management" then to "Advanced" on the left.  You'll see the developmental upgrade there, be sure to use the HTTP one.

**Comment by NicNacke** [comment]
The MQTT Publisher works fine. I get all Data in Home Assistant and can work there with them. 😀

**Comment by chad-ermacora** [comment]
MQTT has now been integrated into the program as of Beta.30.62.

Kootnet Sensors now supports MQTT as a server (Mosquitto Broker), Publisher and Subscriber.
