### ISSUE TITLE
MQTT Connection Refused

### ISSUE THREAD

**Issue by Rapt0rx** [chad-ermacora/sensor-rp#21]
Good Day love using kootnet

Since Beta.32.12 my mqtt stopped working

Kootnet LOG: ERROR:  MQTT Publisher Send Failure: Connection Refused: 
             not authorised.

Mosquitto:  New connection from 192.168.1.52 on port 1883.
            Socket error on client <unknown>, disconnecting.

I did try to reinsert my login details but still the same error

**Comment by chad-ermacora** [comment]
I did just do a big overhaul of MQTT, which changed the dynamic of the login (among other things). Where you only using a username without a password? If so, update to the latest developmental build now (Beta.32.15) and see if that fixes it. If not, I'll have to dig a bit deeper.

**Comment by Rapt0rx** [comment]
I still get the same error on 32.15. I am using a username and a password. I am using Mosquitto in home assistant

**Comment by chad-ermacora** [comment]
I think I found the issue. Update to the latest Dev now (Beta.32.16).

**Comment by Rapt0rx** [comment]
Now it does connect but its not publishing anything. when I set my topic to # in my mqtt client I get nothing. 
And I see now after I change settings in "MQTT Publisher Configuration" menu an click update. I need to go to Advanced and restart Program before the new settings take affect.

**Comment by chad-ermacora** [comment]
I'll set up a password-protected Mosquitto server to help my diagnostics. I'll post again once I figure things out.

**Comment by chad-ermacora** [comment]
Got it fixed. Update to Beta.32.18 and let me know if it's working for you now. 

Thanks again for the bug report.

**Comment by Rapt0rx** [comment]
Thank you it's working now.
one more thing if you can help me I use to be able to split the gas values in home assistant with this 
value_template: "{{value.split(',')[1]}}" 
To only get the value of the different gas values. enviro+
Do you know what i can use to split it with the new way mqtt is formatted

**Comment by chad-ermacora** [comment]
All sensors with multiple values are created as dictionaries now, Here is an example of a Gas transmission. 
{'Gas_Oxidising': 111.3913, 'Gas_Reducing': 220.23318, 'Gas_NH3': 282.46154}

I'm also debating making single values use dictionary format for consistency, but I haven't decided yet. The reason for this change, is I have made it so you can record MQTT subscriber data from other sensors into a single sensor database. The index value, such as "Gas_Oxidising" is used as the SQL database column the value gets written to. Long story short, this allows you to centralize sensor recording if desired. AKA set up multiple Kootnet sensors to send sensor readings to an MQTT broker and have one or more other (or same) sensors subscribe to the MQTT broker and record all readings into a SQL database. I'm now in the process of enhancing the graphing section to work with said MQTT subscriber SQL database.

**Comment by Rapt0rx** [comment]
O oky thanks for the help.
